/*
 * TODO: define error code in this file
 */
#define TFTP_ERROR_FILE_NOT_FOUND 1
#define TFTP_ERROR_INVALID_OPCODE 4
#define TFTP_ERROR_FILE_ALREADY_EXISTS 6
#define TFTP_ERROR_INVALID_ARGUMENT_COUNT 11